name: DiscordChatBridge
main: dev.fread.discordbridge.DiscordChatBridge
version: 1.4.3
api-version: 1.16
author: fread
description: Chat bridge from discord to minecraft and vice versa
commands:
  dchat:
    description: Reload DiscordChatBridge Configuration
    usage: /<command> reload
    permission: dchat.reload
permissions:
  dchat.reload:
    description: Allows you to reload the plugin config
    default: op
