name: DiscordChatBridge
main: dev.fread.discordbridge.DiscordChatBridge
version: 1.4.2
api-version: 1.16
author: fread
description: Чат-мост между Minecraft и Discord
commands:
  dchat:
    description: Перезагрузка конфигурации DiscordChatBridge
    usage: /<command> reload
    permission: dchat.reload
permissions:
  dchat.reload:
    description: Позволяет перезагружать конфиг плагина
    default: op
